# Generated by Django 4.1.7 on 2023-02-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feat_mangafetcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaChapter',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('result', models.JSONField(default=None, null=True)),
                ('lastFetchedAt', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
